---
title: "analyze_tmp"
author: "psadil"
date: "April 25, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(magrittr)
library(stringdist)
library(Hmisc)
library(extrafontdb)
library(extrafont)


cutoff <- 1

source(file.path('utils.R'))
targets <- read_csv('objectNames_2afc.csv') 

out <- list()
for (i in 1:dim(targets[1])){
  out[i] = list(c(targets[i,]$name1, targets[i,]$name2, targets[i,]$name3, targets[i,]$name4, targets[i,]$name5, targets[i,]$name6, targets[i,]$name7, targets[i,]$name8, targets[i,]$name9, targets[i,]$name10))
}



cbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

Conditions = c('Not Studied','CFS, Image', 'Binocular, Image')

colmap <- c('Not Studied'=cbPalette[7]
            ,'Word'=cbPalette[2]
            ,'CFS, Image'=cbPalette[3]
            ,'Binocular, Image'=cbPalette[4])

'%!in%' <- function(x,y)!('%in%'(x,y))


```

Exemplary participants
Subject...
 - 2 didn't give any responses during the test
 - 3 left experiment after second list
 - 4 didn't give any responses
 - 5 didn't give any responses
 - 1,6,7 all gave responses





```{r loadData}



files <- Sys.glob(file.path("data","subject*","CFSRecall","*.csv"))
files <- files[2:length(files)]

d <- lapply(files, read_csv, col_types=cols(pas_1=col_character(),pas_2=col_character())) %>% 
  bind_rows() %>%
  select(subject, pas_2, list, trial_test, tType, item_test, pair_test, tType_test, swap_test, mm_answer, response_cue, response_noise, rt_noise) %>%
  filter(subject %!in% c(3,4,6)) %>%
  filter(list<8) %>%
  rename(condition = tType) %>%
  mutate(targets = out[item_test]) %>%
  mutate(pas_2 = pas_2[trial_test]) %>%
  # mutate(targets = sapply(X=targets, FUN=function(x) unname(unlist(x)))) %>%
  mutate(firstTarget=sapply(X=targets, FUN=function(x) extract2(x,1))) %>%
  mutate(dl = Map(function(x,y) stringdist(x, y, method="dl"), targets, response_cue)) %>%
  mutate(minDist = sapply(X=dl, FUN=function(x) min(x, na.rm=TRUE))) %>%
  mutate(cue_correct = if_else(minDist<cutoff, 1, 0)) %>%
  mutate(mmm_correct = if_else(mm_answer==response_noise, 1, 0)) %>%
  mutate(subject = factor(subject)) %>%
  mutate(list = factor(list)) %>%
  mutate(condition = replace(condition, condition %in% c('NOT STUDIED','CFS','BINOCULAR'), c('Not Studied','CFS, Image', 'Binocular, Image'))) %>%
  mutate(condition = factor(condition, levels =c('Not Studied','CFS, Image','Binocular, Image')))


```

```{r pas2}

d %>%
  filter(condition=="CFS, Image") %>%
  ggplot(aes(x=condition, y=pas_2)) +
  stat_summary(fun.data="mean_cl_boot") +
  # scale_y_continuous(limits = c(0,1), name = "pas_2") +
  ggsave('name_accuracy_group.png') +
  facet_grid(subject~.) +
  ggsave('name_accuracy_sub.png')


```


```{r naming}


d %>%
  ggplot(aes(x=condition, y=cue_correct)) +
  stat_summary(fun.data="mean_cl_boot") +
  scale_y_continuous(limits = c(0,1), name = "Naming Accuracy") +
  theme_classic(base_size = 12, base_family = "Arial") +
  theme(
    axis.ticks = element_blank()
    # , legend.key.height = unit(1.5,'lines')
    , axis.line = element_line(size=1)
    , plot.margin=margin(rep(0,4))
  ) +
  ggsave('name_accuracy_group.png') +
  facet_grid(subject~.) +
  ggsave('name_accuracy_sub.png')


```

```{r mmm}

d %>%
  ggplot(aes(x=condition, y=mmm_correct)) +
  stat_summary(fun.data="mean_cl_boot") +
  scale_y_continuous(limits = c(0,1), name = "Match/Mismatch Accuracy") +
  ggsave('mmm_accuracy_group.png') +
  facet_grid(subject~.) +
  ggsave('mmm_accuracy_sub.png')

```

```{r noise_rt}

labels <- c('0' = "Not Named", '1' = "Name")
labels_mmm <- c('0' = "Incorrect", '1' = "Correct")

d %>%
  filter(mmm_correct %in% c(0,1)) %>%
  ggplot(aes(x=condition, y=rt_noise, fill=condition)) +
  scale_y_continuous(limits = c(0,12), name = "Match/Mismatch RT") +
  scale_fill_manual(values=colmap, name= "Condition") +
  geom_violin() +
  facet_grid(mmm_correct~cue_correct, labeller = labeller(cue_correct = labels, mmm_correct=labels_mmm)) +
  ggsave('mmm_rt_group.png') +
  facet_grid(subject~cue_correct, labeller = labeller(cue_correct = labels)) +
  ggsave('mmm_rt_sub.png')


d %>%
  filter(mmm_correct %in% c(0,1)) %>%
  ggplot(aes(x=condition, fill=condition)) +
  scale_y_continuous(name = "N Trials") +
  scale_fill_manual(values=colmap, name= "Condition") +
  geom_bar() +
  facet_grid(mmm_correct~cue_correct, labeller = labeller(cue_correct = labels, mmm_correct=labels_mmm)) +
  ggsave('nMMM_group.png') +
  facet_grid(subject~cue_correct, labeller = labeller(cue_correct = labels)) +
  ggsave('nMMM_sub.png')


```
