---
title: "analyze_humans"
author: "pss"
date: "April 7, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

library(tidyverse)
library(magrittr)
library(Hmisc)

```


```{r loadData}
dir_data <- "data"
files <- list.files(pattern="*.csv", recursive=TRUE, path=dir_data)
d <- lapply(file.path("data",files) , read_csv, col_types=cols(pas=col_character())) %>% 
  bind_rows() %>%
  select(-seed,-dominantEye,-sex,-ethnicity,-eyes_1,-eyes_2,-tStart,-tEnd,-race) %>%
  filter(tType=='CFS') %>%
  mutate(subject=factor(subject))

```


```{r grandAverage}

d %>%
  filter(exitFlag!='SPACE') %>%
  ggplot(mapping=aes(x=trial, y=rt)) +
  geom_smooth() +
  ylim(c(0,10))


```

```{r subjects}

d %>%
  filter(subject==6) %>%
  # filter(exitFlag!='SPACE') %>%
  ggplot(mapping=aes(x=trial, y=rt, color=subject)) +
  geom_line() +
  ylim(c(0,10))

d %>%
  filter(subject %in% c(1,5,6,7)) %>%
  filter(exitFlag!='SPACE') %>%
  ggplot(mapping=aes(x=trial, y=rt)) +
  facet_grid(subject~.) +
  geom_line() +
  coord_cartesian(ylim=c(0,5)) +
  ggsave('rt_bySub.png')

```


```{r transparency}

d %>%
  filter(subject %in% c(1,5,6,7)) %>%
  filter(exitFlag!='SPACE') %>%
  ggplot(mapping=aes(x=trial, y=transparency)) +
  facet_grid(subject~.) +
  geom_line() +
  coord_cartesian(ylim=c(0,1)) +
  ggsave('opacity_bySub.png')

d %>%
  filter(subject==6) %>%
  # filter(exitFlag!='SPACE') %>%
  ggplot(mapping=aes(x=trial, y=transparency, color=subject)) +
  geom_line()

```


```{r, histograms}

d %>%
  filter(exitFlag!='SPACE') %>%
  ggplot(mapping=aes(rt)) +
  geom_histogram()

```

## Ideal 

```{r}

weibullParams <- function(mu, sd){
  shape <- (sd/mu)^-1.086
  scale <- mu/(gamma(1+1/shape))
  
  out <- list(scale=scale,shape=shape)
  return(out)
}

params <- weibullParams(mu=3,sd=1)

tibble(subject=rep(0,times=100)) %>%
  mutate(trial=1:100) %>%
  mutate(rt = rweibull(100,shape=params$shape, scale=params$scale)) %>%
  ggplot(., mapping=aes(x=trial, y=rt)) +
  geom_line() +
  coord_cartesian(ylim=c(0,5)) +
  ggsave("sim_rt_wbl_mu3_sd1.png")
  

```

