---
title: "analyze_robots"
author: "pss"
date: "April 7, 2017"
output: html_document
params:
  data_dir: robo
  expt: CFSRecall
  
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE,
                      fig.path = file.path('output','figures'))

library(tidyverse)
library(magrittr)
library(stringdist)
library(Hmisc)
library(extrafontdb)
library(extrafont)

cutoff <- 1

source(file.path('utils.R'))
targets <- read_csv('objectNames_2afc.csv') 

out <- list()
for (i in 1:dim(targets[1])){
  out[i] = list(c(targets[i,]$name1, targets[i,]$name2, targets[i,]$name3, targets[i,]$name4, targets[i,]$name5, targets[i,]$name6, targets[i,]$name7, targets[i,]$name8, targets[i,]$name9, targets[i,]$name10))
}

cbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

Conditions = c('Not Studied','CFS, Image', 'Binocular, Image')

colmap <- c('Not Studied'=cbPalette[7]
            ,'Word'=cbPalette[2]
            ,'CFS, Image'=cbPalette[3]
            ,'Binocular, Image'=cbPalette[4])

'%!in%' <- function(x,y)!('%in%'(x,y))

```


```{r loadData, message=FALSE}

s_dirs <- list.files(path=params$data_dir)
files <- list.files(path=file.path(params$data_dir,s_dirs,params$expt), pattern = ".csv")
d <- lapply(file.path(params$data_dir,s_dirs,params$expt,files) , read_csv) %>% 
  bind_rows() %>%
  select(subject, pas_2, list, trial_test, item_test, pair_test, tType_test, name_test, gonogo_answer, response_cue, rt_cue, RoboRT_cue, response_noise, rt_noise, RoboRT_noise, meanRoboRT_noise, jitter_noise) %>%
  mutate(subject=factor(subject)) %>%
  mutate(noise_correct = if_else((gonogo_answer=='go' & response_noise=='Return') |
                                   (gonogo_answer=='nogo' & response_noise!='Return'), 1, 0)) %>%
  select(-response_noise)
  
  

```


```{r quantiles}

p <- c(.1, .3, .5, .7, .9)

d[rep(seq(from=1, to=dim(d)[1]),times=5),] %>%
  select(rt_noise, tType_test) %>%
  mutate(quant = rep(p, each=dim(d)[1])) %>%
  mutate(tType_test = factor(tType_test, levels=c('Not Studied','CFS','Binocular'))) %>%
  group_by(tType_test, quant) %>%
  summarise(qu = quantile(rt_noise, mean(quant), na.rm=TRUE)) %>%
  ggplot(aes(x=qu, y=quant, color=tType_test)) +
  geom_line()
  

d %>%
  select(rt_noise, tType_test) %>%
  mutate(tType_test = factor(tType_test, levels=c('Not Studied','CFS','Binocular'))) %>%
  group_by(tType_test) %>%
  ggplot(aes(x=rt_noise, color=tType_test)) +
  stat_ecdf()


```

