---
title: "explore"
author: "pss"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
params:
  data_dir: data
  expt: CFSgonogo
  cutoff: 2
  percentiles: 5
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, fig.path = paste0(file.path('output','figures',params$expt),.Platform$file.sep))

library(tidyverse)
library(magrittr)
library(stringdist)
library(Hmisc)
library(extrafontdb)
library(extrafont)


source(file.path('utils.R'))
targets <- read_csv('objectNames_2afc.csv') 

out <- list()
for (i in 1:dim(targets[1])){
  out[i] = list(c(targets[i,]$name1, targets[i,]$name2, targets[i,]$name3, targets[i,]$name4, targets[i,]$name5, targets[i,]$name6, targets[i,]$name7, targets[i,]$name8, targets[i,]$name9, targets[i,]$name10))
}

cbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

Conditions = c('Not Studied','CFS, Image', 'Binocular, Image')

colmap <- c('Not Studied'=cbPalette[7]
            ,'Word'=cbPalette[2]
            ,'CFS'=cbPalette[3]
            ,'Binocular'=cbPalette[4])

old_theme <- theme_set(theme_classic(base_size = 12, base_family = "Arial")) +
  theme_update(
    axis.ticks = element_blank()
    , axis.line = element_line(size=1)
    , plot.margin=margin(rep(0,4))
  )

```


```{r loadData, message=FALSE}

s_dirs <- list.files(path=params$data_dir)
files <- list.files(path=file.path(params$data_dir,s_dirs,params$expt), pattern = ".csv")
d <- lapply(file.path(params$data_dir,s_dirs,params$expt,files) , read_csv) %>% 
  bind_rows() %>%
  select(subject, pas_2, list, trial_test, item_test, tType_test, name_test, gonogo_answer, response_cue, rt_cue, response_noise, rt_noise) %>%
  mutate(noise_correct = if_else((gonogo_answer=='go' & response_noise=='Return') |
                                   (gonogo_answer=='nogo' & response_noise!='Return'), 1, 0)) %>%
  mutate(subject=factor(subject)) %>%
  mutate(targets = out[item_test]) %>%
  mutate(firstTarget=sapply(X=targets, FUN=function(x) extract2(x,1))) %>%
  mutate(dl = Map(function(x,y) stringdist(x, y, method="dl"), targets, response_cue)) %>%
  mutate(minDist = sapply(X=dl, FUN=function(x) min(x, na.rm=TRUE))) %>%
  mutate(cue_correct = if_else(minDist<params$cutoff, 1, 0)) %>%
  rename(Condition = tType_test) %>%
  mutate(Condition = factor(Condition, levels = c("Not Studied","CFS","Binocular"))) %>%
  mutate(pas_2 = as.numeric(substring(pas_2,1,1))) %>%
  mutate(pas_2 = if_else(is.na(pas_2),0,pas_2)) %>%
  mutate(pas_2 = factor(pas_2)) %>%
  mutate(id = 1:n())
  

# d %>% 
#   mutate(id = 1:n()) %>%
#   select(firstTarget, response_cue, minDist, cue_correct, id) %>%
#   write_csv(x=., path = file.path("tmp2.csv"))

d2 <- read_csv("tmp.csv") %>%
  full_join(., d, by=c("id","firstTarget","response_cue","minDist"))


```


```{r pas2}

d %>%
  filter(Condition=="CFS") %>%
  ggplot(aes(x = pas_2)) +
  geom_bar() +
  # stat_summary(fun.data="mean_cl_boot") +
  # scale_y_continuous(limits = c(0,1), name = "pas_2") +
  # ggsave('pas.png') +
  facet_grid(subject~.) +
  # ggsave('pas_sub.png')


```


```{r naming}


d2 %>%
  ggplot(aes(x=Condition, y=cue_correct.y, color = Condition)) +
  stat_summary(fun.data="mean_cl_boot") +
  scale_y_continuous(limits = c(0,1), name = "Naming Accuracy") +
  scale_color_manual(values=colmap, name= "Condition") +
  ggsave('name_accuracy_group.png') +
  # ggsave('name_accuracy_group.png', path = file.path(knitr::opts_chunk$get("fig.path"))) +
  facet_grid(subject~.) +
  geom_hline(yintercept = 0) +
  geom_hline(yintercept = .5, linetype = "dashed") +
  scale_y_continuous(limits = c(0,1), breaks = c(0,.5,1), name = "Naming Accuracy") +
  ggsave('name_accuracy_sub.png', height = 14)
  # ggsave('name_accuracy_sub.png', path = file.path(knitr::opts_chunk$get("fig.path")))


```

```{r noise_correct}

d2 %>%
  ggplot(aes(x=Condition, y=noise_correct, color = Condition)) +
  stat_summary(fun.data="mean_cl_boot") +
  scale_y_continuous(limits = c(0,1), name = "Go/No-Go Accuracy") +
  scale_color_manual(values=colmap, name= "Condition") +
  ggsave('noise_accuracy_group.png')  +
  facet_grid(subject~.) +
  geom_hline(yintercept = 0) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  scale_y_continuous(limits = c(0,1), breaks = c(0,.5,1), name = "Naming Accuracy") +
  ggsave('noise_accuracy_sub.png', height = 14) 

```



```{r ecdf}


d2 %>%
  filter(gonogo_answer == "go" 
         & noise_correct==1
         & cue_correct.y==0) %>%
  ggplot(aes(x=rt_noise, color=Condition)) +
  scale_y_continuous(limits = c(0,1), name = "eCDF") +
  scale_x_continuous(name = "RT on (Correct) go trials") +
  scale_color_manual(values=colmap, name= "Condition") +
  stat_ecdf() +
  ggsave('noise_ecdf_group.png') +
  facet_grid(subject~.) +
    geom_hline(yintercept = 0) +
  geom_hline(yintercept = .5, linetype = "dashed") +
  scale_y_continuous(limits = c(0,1), breaks = c(0,.5,1), name = "eCDF") +
  ggsave('noise_ecdf_sub.png', height = 14)
  


```

13 participants. 120 items per participant encountered in lists of 12 items. With 3 conditions (binocular, cfs, not-studied), there were 4 items in each condition in each list. Of those four items, 3 were encountered in a “go” test trial, and 1 was in a “no-go” test trial. So, 1/4 of test-trials were no-go. This leaves 30 items in go trials per condition, per participant.



```{r percentiles}

p <- seq(from=.2, to=1, length.out = 5)

tmp <- d2 %>%
  filter(gonogo_answer == "go" 
         & noise_correct==1
         & cue_correct.y==0)

d2[rep(seq(from=1, to=dim(d)[1]),times=length(p)),] %>%
  filter(gonogo_answer == "go" 
         & noise_correct==1
         & cue_correct.y==0) %>%
  mutate(Percentile = rep(p, each=dim(tmp)[1])) %>%
  group_by(Condition, Percentile) %>%
  summarise(RT = quantile(rt_noise, mean(Percentile), na.rm=TRUE)) %>%
  # mutate(Percentile = factor(Percentile)) %>%
  ggplot(aes(x=RT, y=Percentile, color=Condition)) +
  geom_point() +
  scale_y_continuous(limits = c(0,1), breaks = p, name = "CDF") +
  scale_x_continuous(limits = c(0,5), name = "RT on (Correct) go trials") +
  scale_color_manual(values=colmap, name= "Condition") +
  ggsave('noise_percentiles_group.png') 


d2[rep(seq(from=1, to=dim(d)[1]),times=length(p)),] %>%
  filter(gonogo_answer == "go" 
         & noise_correct==1
         & cue_correct.y==0) %>%
  select(rt_noise, Condition) %>%
  mutate(Percentile = rep(p, each=dim(tmp)[1])) %>%
  group_by(Condition, Percentile) %>%
  summarise(RT = quantile(rt_noise, mean(Percentile), na.rm=TRUE)) %>%
  ggplot(aes(x=Percentile, y=RT, color=Condition)) +
  geom_point() +
  scale_x_continuous(limits = c(0,1), breaks = p, name = "CDF") +
  scale_y_continuous(limits = c(0,5), name = "RT on (Correct) go trials") +
  scale_color_manual(values=colmap, name= "Condition") +
  ggsave('noise_percentilesT_group.png') 


```

```{r percentiles_sub}

d2[rep(seq(from=1, to=dim(d)[1]),times=length(p)),] %>%
  filter(gonogo_answer == "go" 
         & noise_correct==1
         & cue_correct.y==0) %>%
  mutate(Percentile = rep(p, each=dim(tmp)[1])) %>%
  group_by(Condition, Percentile, subject) %>%
  summarise(RT = quantile(rt_noise, mean(Percentile), na.rm=TRUE)) %>%
  ggplot(aes(x=RT, y=Percentile, color=Condition)) +
  geom_line() +
  scale_y_continuous(limits = c(0,1), breaks = p, name = "CDF") +
  scale_x_continuous(limits = c(0,5), name = "RT on (Correct) go trials") +
  scale_color_manual(values=colmap, name= "Condition") +
  facet_grid(subject~.) +
  ggsave('noise_percentiles_sub.png', height=14) 


d2[rep(seq(from=1, to=dim(d)[1]),times=length(p)),] %>%
  filter(gonogo_answer == "go" 
         & noise_correct==1
         & cue_correct.y==0) %>%
  select(rt_noise, Condition, subject) %>%
  mutate(Percentile = rep(p, each=dim(tmp)[1])) %>%
  group_by(Condition, Percentile, subject) %>%
  summarise(RT = quantile(rt_noise, mean(Percentile), na.rm=TRUE)) %>%
  ggplot(aes(x=Percentile, y=RT, color=Condition)) +
  geom_line() +
  scale_x_continuous(limits = c(0,1), breaks = p, name = "CDF") +
  scale_y_continuous(limits = c(0,5), name = "RT on (Correct) go trials") +
  scale_color_manual(values=colmap, name= "Condition")+
  facet_grid(subject~.) +
  ggsave('noise_percentilesT_sub.png', height=14)


```


```{r rt_distributions}

d2[rep(seq(from=1, to=dim(d)[1]),times=length(p)),] %>%
  filter(gonogo_answer == "go" 
         & noise_correct==1
         ) %>%
  ggplot(aes(x = Condition, y=rt_noise, fill = Condition)) +
  geom_violin(draw_quantiles = c(.1,.3,.5,.7,.9), scale = "area") +
  # geom_jitter(height = 0, width = 0.2) +
  scale_y_continuous(limits = c(0,5), name = "RT on (Correct) go trials") +
  scale_color_manual(values=colmap, name= "Condition") +
  ggsave('noise_violin_group.png') +
  facet_grid(subject~.) +
  ggsave('noise_violin_sub.png', height = 14) 


d2[rep(seq(from=1, to=dim(d)[1]),times=length(p)),] %>%
  filter(gonogo_answer == "go" 
         & noise_correct==1
         & cue_correct.y==0) %>%
  ggplot(aes(x = Condition, y=rt_noise, fill = Condition)) +
  geom_violin(draw_quantiles = c(.1,.3,.5,.7,.9), scale = "area") +
  # geom_jitter(height = 0, width = 0.2) +
  scale_y_continuous(limits = c(0,5), name = "RT on (Correct) go trials that weren't named") +
  scale_color_manual(values=colmap, name= "Condition") +
  ggsave('noise_violin_noname_group.png') +
  facet_grid(subject~.) +
  ggsave('noise_violin_noname_sub.png', height=14) 


```

