function [] = giveInstruction(window, keys, responseHandler, constants, expt)


switch expt
    case 'occularDominance'
        showPromptAndWaitForResp(window, 'Use the arrow keys to say which direction you think the arrow faced.',...
            keys,constants,responseHandler);
        showPromptAndWaitForResp(window, 'Keep your eyes focused on the center white square',...
            keys,constants,responseHandler);
                
    case 'staircase'
        showPromptAndWaitForResp(window, 'In this experiment, you will see hidden objects emerge from flashing squares',...
            keys,constants,responseHandler);
        showPromptAndWaitForResp(window, ['When you are certain that an object has emerged, press the Enter key.\n',...
            'Please press the key as soon as you are certain that an object has appeared.\n',...
            'But, do NOT wait until you can identify the object.'],...
            keys,constants,responseHandler);
        showPromptAndWaitForResp(window, ['After each trial, you will be asked about how well you could see the object.\n\n',...
            'no image detected - 0\n',...
            'possibly saw, couldn''t name - 1\n',...
            'definitely saw, but unsure what it was (could possibly guess) - 2\n',...
            'definitely saw, could name - 3\n',...
            '\nYou should wait until you can give a response of 2\n',...
            'but respond before you would give a response of 3\n', ...
            '\nUse the keypad to indicate your response\n'],...
            keys,constants,responseHandler);
        showPromptAndWaitForResp(window, ['On some trials, there will be no object\n',...
            'If you think that there is no object, press SPACE'],...
            keys,constants,responseHandler);
        showPromptAndWaitForResp(window, 'Finally, always keep your eyes focused on the center white cross',...
            keys,constants,responseHandler);       
        
end

iti(window, 1);


end